---

- name: Installing grafana
  shell: helm install --name grafana stable/grafana

- name: Exporting Pod name
  shell: export POD_NAME=$(kubectl get pods --namespace default -l "app=grafana,release=grafana" -o jsonpath="{.items[0].metadata.name}")

- name: Getting the login password for user admin
  shell: kubectl get secret --namespace default grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
  register: grafpwd

- debug: var=grafpwd.stdout_lines[0]

- name: forwarding to localhost port 3000
  shell: kubectl --namespace default port-forward $POD_NAME 3000

- include_tasks: roles/helm/grafana/tasks/grafana_datasources.yaml

- include_tasks: roles/helm/grafana/tasks/grafana_dashboard.yaml
