---

- name: Setting up the kubernetes cluster
  command: kops create cluster --node-size t2.medium --master-size t2.medium --kubernetes-version=1.13.0 --zones=us-east-1b,us-east-1c,us-east-1d --master-zones=us-east-1b,us-east-1c,us-east-1d --node-count={{node_count}} --name={{ cluster_name }} --state={{ state_store }}


- name: Creating the cluster
  command: kops update cluster {{ cluster_name }} --state={{ state_store }} --yes

- pause:
    minutes: 1

- name: Validating cluster
  command: kops validate cluster --name={{ cluster_name }} --state={{ state_store }}
  register: result
  until: result.stdout.find("is ready") != -1
  retries: 10
  delay: 60