---

- name: Setting up the kubernetes cluster
  command: kops create cluster --node-size t2.micro --master-size t2.micro --kubernetes-version=1.13.0 --zones=us-east-1b --master-zones=us-east-1b --node-count=1 "{{ domain }}"

#- name: Creating the cluster
#  command: kops update cluster k8.csye6225-fall2018-gaikawads.me --yes