---

- name: Create S3 policy from template
  iam_policy:
    iam_type: role
    iam_name: nodes.k8s.csye6225-fall2018-gaikawads.me
    policy_name: "S3-Access"
    state: present
    policy_json: " {{ lookup( 'template', 'policy.json') }} "
