---
- name: Create IAM role with custom trust relationship
  iam:
    iam_type: role
    name: EC2serviceRole
    state: present
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    managed_policy:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
    trust_policy:
      Version: '2012-10-17'
      Statement:
      - Action: sts:AssumeRole
        Effect: Allow
        Principal:
          Service: ec2.amazonaws.com


