- name: Set ecr repo in jenkins 
  shell: sed 's/aws_repo/{{ecr_repo}}/g' roles/helm/jenkins/tasks/values_template.yaml > roles/helm/jenkins/tasks/values.yaml 

- name: Installing jenkins
  shell: helm install --name jenkins -f roles/helm/jenkins/tasks/values.yaml --set abe=test stable/jenkins

- name: cluster binding jenkins
  shell: kubectl -n default create rolebinding jenkins-binding --clusterrole=cluster-admin --serviceaccount=default:default

- pause:
    seconds: 5

- name: Generate Name of token for ServiceAccount jenkins
  command: kubectl -n default get serviceaccount default -o go-template --template='{% raw %}{{range .secrets}}{{.name}}{{"\n"}}{{end}}{% endraw %}'
  register: jenkins_token

- debug: var=jenkins_token

- name: Generate token of ServiceAccount
shell: kubectl -n default get secrets {{jenkins_token.stdout}} -o go-template --template '\{\{index .data "token"\}\}'