---

- name: helm initialization
  command: helm init


- name: creating service account tiller
  command: kubectl create serviceaccount --namespace kube-system tiller

- name: creating cluster role binding
  command: kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller

- name: deploy tiller
  command: kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
