---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: csye7374-rc
spec:
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: csye7374-rc