---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-demo
spec:
  hard:
    requests.cpu: 1000m
    requests.memory: 2Gi
    limits.cpu: 1000m
    limits.memory: 2Gi
    pods: 100
    persistentvolumeclaims: "5"
    requests.storage: "50Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-demo
spec:
  limits:
  - type: Container
    default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 128Mi
      cpu: 100m
    max:
      memory: 512Mi
      cpu: 500m
    min:
      memory: 128Mi
      cpu: 100m
  - type: PersistentVolumeClaim
    max:
      storage: 20Gi
    min:
      storage: 1Gi