---
apiVersion: v1
kind: Service
metadata:
  name: csye7374-elb
spec:
  type: LoadBalancer             
  ports:
  - port: 80                 
    targetPort: 8080         
    nodePort: 30130          
  selector:
    app: csye7374