---
apiVersion: v1               
kind: Pod                    
metadata:
  name: csye7374
  labels:                                                 
    app: csye7374         
spec:
  containers:
  - image: {{ ecr_repo }}       
    name: csye7374            
    ports:
    - containerPort: 8080    
      protocol: TCP