---
apiVersion: v1               
kind: Pod                    
metadata:
  name: csye7374
  labels:
    app: csye7374    
spec:
  containers:
  - image: "{{ ..Ansible.group_vars.all.vars.ecr_repo }}/csye7374:latest"
    name: csye7374            
    ports:
    - containerPort: 8080    
      protocol: TCP