---
apiVersion: v1               
kind: Pod                    
metadata:
  name: csye7374
  labels:
    app: csye7374    
spec:
  containers:
  - image: abc/csye7374:latest
    name: csye7374            
    ports:
    - containerPort: 8080    
      protocol: TCP
    # env:
    #   - name: abc
    #     valueFrom:
    #       configMapKeyRef:
    #         name: special-config
    #         key: abc