---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csye7374-app-profile
data:
  profile: dev

---
apiVersion: v1
kind: Secret
metadata:
  name: csye7374-config-db-config
stringData:                                    
  DB_USER: csye7374master
data:
  DB_PASSWD: Y3N5ZTczNzRwYXNzd29yZA==

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-ebs-slow-lab07
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: csye7374-rc
spec:
  serviceName: stateful-sets-lab7
  replicas: 3
  selector:
    matchLabels:
      app: csye7374
  template:
    metadata:
      labels:
        app: csye7374
    spec:
      containers:
      - image: ecr_repo/csye7374:latest       
        name: csye7374
        imagePullPolicy: IfNotPresent 
        env:

        - name: SPRING_PROFILES_ACTIVE
          valueFrom:                     
            configMapKeyRef:             
              name: csye7374-app-profile
              key: profile
        
        - name: bucketName                
          valueFrom:                     
            configMapKeyRef:             
              name: csye7374-app-bucket
              key: bucket_name
        
        - name: SPRING_DATASOURCE_URL              
          valueFrom:                     
            configMapKeyRef:             
              name: db-endpoint     
              key: db_endpoint
        
        - name: SPRING_DATASOURCE_USERNAME               
          valueFrom:                     
            secretKeyRef:             
              name: csye7374-config-db-config     
              key: DB_USER
        
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:                     
            secretKeyRef:             
              name: csye7374-config-db-config
              key: DB_PASSWD
        livenessProbe:
          httpGet:
            path: /user/testdbs3
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /user/testdbs3
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 20        
        ports:
        - containerPort: 8080    
          protocol: TCP
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: /aws-ebs-vol
          name: data
  volumeClaimTemplates:
  - metadata:                        
      name: data                     
    spec:
      storageClassName: aws-ebs-slow-lab07                        
      resources:                     
        requests:                    
          storage: 1Gi               
      accessModes:                   
      - ReadWriteOnce 

---
apiVersion: v1
kind: Service
metadata:
  name: csye7374-elb
spec:
  type: LoadBalancer             
  ports:
  - port: 80                 
    targetPort: 8080         
    nodePort: 30130          
  selector:
    app: csye7374