---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csye7374-app-config
data:
  s3_bucket: s3_bucket_endpoint

---
apiVersion: v1
kind: Secret
metadata:
  name: csye7374-config-db-config
stringData:                                    
  DB_USER: mysql
data:
  DB_PASSWD: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: csye7374-rc
spec:
  replicas: 1
  selector:
    app: csye7374
  template:
    metadata:
      labels:
        app: csye7374
    spec:
      containers:
      containers:
      - image: ecr_repo/csye7374:latest       
        name: csye7374 
        env:
        - name: s3_endpoint                
          valueFrom:                     
            configMapKeyRef:             
              name: csye7374-app-config     
              key: s3_bucket
        - name: DB_USER                
          valueFrom:                     
            secretKeyRef:             
              name: csye7374-config-db-config     
              key: DB_USER
        - name: DB_PASSWD                
          valueFrom:                     
            secretKeyRef:             
              name: csye7374-config-db-config     
              key: DB_PASSWD
        imagePullPolicy: Never
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        ports:
        - containerPort: 8080    
          protocol: TCP
        resources:
          limits:
            memory: "8Mi"
            cpu: "1m"
          requests:
            memory: "8Mi"
            cpu: "1m"

---
apiVersion: v1
kind: Service
metadata:
  name: csye7374-elb
spec:
  type: NodePort             
  ports:
  - port: 80                 
    targetPort: 8080         
    nodePort: 30130          
  selector:
    app: csye7374