---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csye7374-app-profile
data:
  profile: dev

---
apiVersion: v1
kind: Secret
metadata:
  name: csye7374-config-db-config
stringData:                                    
  DB_USER: csye7374master
data:
  DB_PASSWD: Y3N5ZTczNzRwYXNzd29yZA==

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: csye7374-rc
spec:
  replicas: 1
  selector:
    app: csye7374
  template:
    metadata:
      labels:
        app: csye7374
    spec:
      containers:
      - image: ecr_repo/csye7374:latest       
        name: csye7374 
        env:
        - name: bucketName                
          valueFrom:                     
            configMapKeyRef:             
              name: csye7374-app-bucket
              key: bucket_name
        
        - name: -Dspring.datasource.url                
          valueFrom:                     
            configMapKeyRef:             
              name: db-endpoint     
              key: db_endpoint
        
        - name: -Dspring.datasource.username                
          valueFrom:                     
            secretKeyRef:             
              name: csye7374-config-db-config     
              key: DB_USER
        
        - name: -Dspring.datasource.password                
          valueFrom:                     
            secretKeyRef:             
              name: csye7374-config-db-config
              key: DB_PASSWD
        
        - name: -Dspring.profiles.active
          valueFrom:                     
            configMapKeyRef:             
              name: csye7374-app-profile
              key: profile
        ports:
        - containerPort: 8080    
          protocol: TCP
        resources:
          limits:
            memory: "500m"
            cpu: "256Mi"
          requests:
            memory: "250m"
            cpu: "128Mi"

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: csye7374-elb
# spec:
#   type: NodePort             
#   ports:
#   - port: 80                 
#     targetPort: 8080         
#     nodePort: 30130          
#   selector:
#     app: csye7374