
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: csye7374-pdb
spec:
  minAvailable: 1         
  selector:                
    matchLabels:           
      app: csye7374-rc   