---

apiVersion: v1
kind: Pod
metadata:
  name: csye7374s
  labels:
    app: jenkins
    component: agent
spec:
  containers:
    - name: dind
      image: docker:18.05-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage