---

- hosts: localhost
  connection: local
  tasks:

  - name: Autoscaling the cluster
    command: kubectl apply -f ../k8s/app/clusterAutoScaler.yaml  

  # - name: Set ECR repo name in comtainer env
  #   command: kubectl create configmap special-config --from-literal=ecr_repo={{ecr_repo}}

  - name: Setting up the kubernetes cluster - configMaps
    command: kubectl apply -f ../k8s/app/ConfigMaps.yaml

  - name: Setting up the kubernetes cluster - Secrets
    command: kubectl apply -f ../k8s/app/DB-Secrets.yaml
  
  - name: Setting up the limits
    command: kubectl apply -f ../k8s/app/limits.yaml

  - name: set the repo name in pod config
    shell: sed 's/ecr_repo/{{ecr_repo}}/g' ../k8s/app/pod_template.yaml > ../k8s/app/pod.yaml
  
  - name: Setting up the kubernetes cluster
    command: kubectl apply -f ../k8s/app/pod.yaml

  - name: Setting up the kubernetes cluster - load Balancer
    command: kubectl apply -f ../k8s/app/loadBalancer.yaml

  - pause:
      seconds: 60

  - name: Setting up the autoscaling
    command: kubectl apply -f ../k8s/app/autoscaler.yaml

  - name: Setting up the policy disruption
    command: kubectl apply -f ../k8s/app/policydis.yaml
    
  - name: Forwarding to port 8888
    command: kubectl port-forward service/csye7374-elb 8888:80
    register: result

  - debug: var=result.stdout_lines
