---

- ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{cluster_name}}"
  register: vpc

- debug: var=vpc.vpcs[0].id

- name: Creating RDS security group
  ec2_group:
    name: dbserverSecurityGroup
    description: DB security group
    vpc_id: "{{vpc.vpcs[0].id}}"
    rules:
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: 0.0.0.0/0
  register: sg_rds

- debug: var=sg_rds.group_id

- ec2_vpc_subnet_facts: 
    filters:
      vpc-id: "{{vpc.vpcs[0].id}}"
  register: subnet

- debug: var=subnet.subnets[0].id
- debug: var=subnet.subnets[1].id

- rds_subnet_group:
    state: present
    description: RDS Subnet Group Creation
    name: RDS Subnet Group
    region: us-east-1
    subnets:
      - "{{subnet.subnets[0].id}}"
      - "{{subnet.subnets[1].id}}"
  register: rds_subnet

- name: Creating RDS
  rds:
    command: create
    db_name: csye7374
    instance_name: csye7374-spring2019
    db_engine: postgres
    engine_version: 10.5
    size: 5
    instance_type: db.t2.medium
    username: csye7374master
    password: csye774password
    vpc_security_groups: "{{sg_rds.group_id}}"
    subnet: "{{rds_subnet.subnet_group.name}}"
    publicly_accessible: no
    multi_zone: no
    region: us-east-1

- name: Waiting for RDS instance to start
  rds_instance_facts: 
    db_instance_identifier: csye7374-spring2019
  register: rds_facts
  until: rds_facts.instances[0].db_instance_status.find("available") != -1
  retries: 15
  delay: 60

- debug: var=rds_facts.instances[0].db_instance_status
- debug: var=rds_facts.instances[0].endpoint.address