---

- ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{cluster_name}}"
  register: vpc

- debug: var=vpc.vpcs[0].id

- name: Creating RDS security group
  ec2_group:
    name: dbserverSecurityGroup
    description: DB security group
    vpc_id: "{{vpc.vpcs[0].id}}"
    rules:
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: 0.0.0.0/0
  register: sg_rds

- debug: var=sg_rds.group_id

- ec2_vpc_subnet_facts: 
    filters:
      vpc-id: "{{vpc.vpcs[0].id}}"
  register: subnet

- name: create rds instance 
  rds_instance:
    engine: postgres
    db_instance_identifier: csye7374-spring2019
    instance_type: db.t2.medium
    username: csye7374master
    password: csye7374password
    engine_version: 10.5
    vpc_security_group_ids: "{{sg_rds.group_id}}"
    allocated_storage: 5

- name: Creating RDS
  rds:
    command: create
    db_name: csye7374
    instance_name: csye7374-spring2019
    publicly_accessible: no
    multi_zone: no
    region: us-east-1
    
