---

- name: creating log group
  command: aws logs create-log-group --log-group-name kubernetes
  ignore_errors: yes


- name: Installing fluentD cloudwatch
  shell: helm install --name fluentd -f roles/helm/fluentd/tasks/values.yaml incubator/fluentd-cloudwatch
