---

# - name: creating log group
#   command: aws logs create-log-group --log-group-name kubernetes


- name: Installing fluentD cloudwatch
  shell: helm install --name my-release3 -f roles/helm/fluentd/tasks/values.yaml incubator/fluentd-cloudwatch
